import type { CoreEntryLedger, LedgerSource } from './content-ledger';

const source = (id: string, title: string, url: string, locator: string, supports: string): LedgerSource => ({
  id, title, kind: '学术综述', url, locator, checked: true, supports,
});

/** Source-led deepening for entries that were previously navigation-only. */
export const remainingEntryLedgers: Record<string, CoreEntryLedger> = {
  'pt-western-ancient': {
    status: '核验正文｜自审完成', scope: '本条是古典与希腊化哲学的历史入口，连接自然、知识、德性、幸福和城邦等问题；不把“古希腊”写成单一西方起源神话，也不把人物按通向现代的进步阶梯排列。', sectionHeadings: { origin: '时段与问题结构', boundaries: '材料与叙事边界', objections: '内部差异与史学警惕', confusions: '常见误读', historicalContext: '相邻问题' },
    origin: [{ kind: '概括', text: '从前苏格拉底自然探究到苏格拉底、柏拉图、亚里士多德，再到斯多亚、伊壁鸠鲁和怀疑主义，哲学实践围绕论证、教育、生活方式和城邦展开。所谓“古典”并非同一理论，而是一组竞争性问题场。', sourceIds: ['WES-1'] }],
    boundaries: [{ kind: '概括', text: '“希腊罗马哲学”覆盖长时段、多城邦与后来的罗马语境；文本保存、作者归属和后世注释会改变我们能知道什么。用现代学科分工切割其伦理、物理、逻辑和政治，会丢失其相互关联。', sourceIds: ['WES-1'] }],
    objections: [{ kind: '概括', text: '将苏格拉底、柏拉图和亚里士多德写成唯一主线，会遮蔽前苏格拉底、医学、修辞、女性哲学家记录缺失、希腊化学派和罗马接受。回应不是平均罗列，而是说明选取何种问题线及未覆盖的材料。', sourceIds: ['WES-1'] }],
    confusions: [{ kind: '解释性重构', text: '斯多亚的“控制”不等于压抑情感；伊壁鸠鲁的快乐也不等于无节制享乐。' }, { kind: '解释性重构', text: '“古典哲学”不是所有后世西方或全球哲学的起点与标准。' }],
    historicalContext: [{ nodeId: 'pt-being-change', label: '什么存在？变化与同一性如何可能？', note: '自然、实体与变化形成多条古典争论。' }, { nodeId: 'pt-good-life', label: '什么是值得过的生活？', note: '德性、宁静、快乐与城邦生活提供不同路线。' }],
    sources: [source('WES-1', 'SEP：Ancient Greek and Roman Philosophy', 'https://plato.stanford.edu/entries/ancient-greek-roman/', '导论及古典、希腊化、罗马各节', '时段范围、学派差异和问题领域。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '摘要', issue: '原文把多条古典路线压成哲学家名单。', evidence: 'WES-1 按不同时段和学派展开。', revision: '改为问题结构、材料边界和互相竞争的生活方案。' }], remaining: ['希腊化、罗马及保存史的原典选读待补。'], adjacentImpact: '核心问题页链接此处时须标明具体学派而非笼统称“古人”。', nextPriority: '补充前苏格拉底、怀疑主义和女性哲学传统的材料。' },
  },
  'pt-western-medieval': {
    status: '核验正文｜自审完成', scope: '本条讨论拉丁、阿拉伯、希伯来和多语传译语境中的中世纪哲学；不把它贬为古典与近代之间的神学空档，也不把不同一神教传统合为一种哲学。', sectionHeadings: { origin: '时段与传译网络', boundaries: '语言、制度与概念边界', objections: '史学简化的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '中世纪哲学在宗教、法学、医学、教育和文本注释制度中发展。希腊语材料经叙利亚语、阿拉伯语、希伯来语和拉丁语的翻译、选择与再解释进入新的问题网络，传译本身也是概念创造。', sourceIds: ['MED-1'] }],
    boundaries: [{ kind: '概括', text: '“中世纪”是分期名称，不是单一语言或宗教；奥古斯丁、伊本·西那、迈蒙尼德与阿奎那的概念、受众和论证任务不同。理性与启示的关系也不能预设为敌对或和谐的单一图式。', sourceIds: ['MED-1'] }],
    objections: [{ kind: '概括', text: '“希腊思想被保存，后由欧洲复兴”的叙事会抹去翻译者、阿拉伯语哲学、犹太哲学和后续创新。纠正它不意味着否认传递，而是追问谁选择文本、怎样翻译、在何种制度中产生新论证。', sourceIds: ['MED-1'] }],
    confusions: [{ kind: '解释性重构', text: '中世纪哲学不等于只用信仰替代论证；形式逻辑、形而上学和自然哲学在其中高度发展。' }, { kind: '解释性重构', text: '同一术语跨语言出现不证明概念完全相同。' }],
    historicalContext: [{ nodeId: 'pt-islamic-translation', label: '翻译运动与哲学学科的形成', note: '从具体翻译网络进入，而非把其当作被动保管。' }, { nodeId: 'pt-religion-reason', label: '信仰、理性与恶的问题', note: '自然神学、启示和解释权在多种语境中重组。' }],
    sources: [source('MED-1', 'SEP：Medieval Philosophy', 'https://plato.stanford.edu/entries/medieval-philosophy/', '导论、§1–§3', '中世纪哲学的多语、多宗教与学科制度语境。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '历史叙事', issue: '原摘要暗示哲学在欧洲内部线性发展。', evidence: 'MED-1 强调多语种、跨宗教和传译网络。', revision: '改写为传译、注释和制度的共同历史。' }], remaining: ['叙利亚语翻译和法学／医学文本待专门核验。'], adjacentImpact: '伊斯兰历史页和宗教理性页须避免中心—边缘叙事。', nextPriority: '补入阿维森纳、迈蒙尼德、阿奎那原典对读。' },
  },
  'pt-western-contemporary': {
    status: '核验正文｜自审完成', scope: '本条覆盖19世纪至当代多条欧洲、北美及跨区域哲学线路的交叉，不将分析、现象学、马克思主义、女性主义、实用主义与后殖民思想压缩为互不相干的标签。', sectionHeadings: { origin: '多线并行的历史结构', boundaries: '标签与地域边界', objections: '正典与分期的争议', confusions: '常见误读', historicalContext: '相邻问题' },
    origin: [{ kind: '概括', text: '工业资本主义、殖民、战争、民主化、科学与新媒介改变了自由、劳动、语言、经验和知识的问题。不同传统常在同一历史压力下给出相互批评的回答，而非各自封闭发展。', sourceIds: ['CONP-1'] }],
    boundaries: [{ kind: '概括', text: '“现象学”“分析哲学”“存在主义”等是教学和史学分类，能定位某些方法与传承，却不能覆盖人物全部工作或跨越地域与学科的交流。', sourceIds: ['CONP-1'] }],
    objections: [{ kind: '概括', text: '把当代史写成欧洲内部流派竞争会遮蔽女性主义、反殖民、非裔、原住民及全球思想网络。纠正不靠添加几个人名，而要改变问题、档案、制度和权力如何进入叙事。', sourceIds: ['CONP-1'] }],
    confusions: [{ kind: '解释性重构', text: '“分析”不等于没有历史和政治，“大陆”不等于反论证；这些标签都包含内部差异。' }, { kind: '解释性重构', text: '同一个“自由”在存在主义、马克思主义和女性主义中未必指同一对象。' }],
    historicalContext: [{ nodeId: 'pt-history-tech', label: '历史、文化与技术怎样塑造共同生活？', note: '现代技术、劳动和媒介是多条思想线的共同问题。' }, { nodeId: 'pt-identity-oppression', label: '身份、压迫与认识不公如何形成？', note: '将性别、种族和殖民放回正典构成而非附录。' }],
    sources: [source('CONP-1', 'SEP：Phenomenology', 'https://plato.stanford.edu/entries/phenomenology/', '导论、历史与方法相关章节', '现象学的方法、历史定位及其同其他传统的关联。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '摘要', issue: '原文仅列流派，没有说明共同历史问题。', evidence: 'CONP-1 显示现象学自身已涉及多重方法与历史。', revision: '加入现代制度、技术与正典争议的入口。' }], remaining: ['实用主义、马克思主义、女性主义和后殖民专门史料待逐支核验。'], adjacentImpact: 'AI、身份、技术页可在此进入，但须回到具体传统。', nextPriority: '分设劳动、殖民与女性主义的阅读路径。' },
  },
  'pt-daoism': {
    status: '核验正文｜自审完成', scope: '本条以《老子》《庄子》及其复杂文本史为入口讨论道、自然、无为与视角；不把道家化为消极不行动、神秘主义或现代环保口号。', sectionHeadings: { origin: '文本与问题起点', boundaries: '概念与文本边界', objections: '内部解释争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '哲学道家文本以道、德、自然、无为、变化和言说限制等问题反思行动与治理。《老子》与《庄子》的成书、层累和注释传统复杂，不能直接把整部文本归为单一作者的稳定教义。', sourceIds: ['DAO-1', 'DAO-2'] }],
    boundaries: [{ kind: '概括', text: '无为通常不是完全不行动，而涉及避免强作、过度控制和不合时宜的干预；自然也不是简单的“野外自然”。这些概念须置于修身、政治、语言和宇宙论的不同段落。', sourceIds: ['DAO-1'] }],
    objections: [{ kind: '概括', text: '把顺应解释为放弃判断，会难以说明批评暴政、处理伤害和学习技艺；《庄子》的视角反思也不必推出所有判断等价。解释者需说明何种行动被反对、何种熟练或回应被肯定。', sourceIds: ['DAO-2'] }],
    confusions: [{ kind: '解释性重构', text: '无为不等于懒惰，顺其自然也不等于永不改变关系或制度。' }, { kind: '解释性重构', text: '道家与道教宗教传统有历史交叠，但“哲学道家”是后设分类，不能抹去多样实践。', sourceIds: ['DAO-1'] }],
    historicalContext: [{ nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '礼、学习和行动的争论应放进互相批评而非儒道二元。' }, { nodeId: 'pt-being-change', label: '什么存在？变化与同一性如何可能？', note: '变化、命名和固定分类可由此进入不同问题。' }],
    sources: [source('DAO-1', 'SEP：Daoism', 'https://plato.stanford.edu/entries/daoism/', '导论、§1–§4', '道、无为、自然及文本／传统边界。'), source('DAO-2', 'SEP：Zhuangzi', 'https://plato.stanford.edu/entries/zhuangzi/', '导论及视角、语言、行动相关章节', '《庄子》的视角反思与解释争议。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜无为', issue: '原文将无为写作不行动。', evidence: 'DAO-1、DAO-2 均将其放入行动、自然与情境问题。', revision: '改为反强作和合宜回应，并保留争议。' }], remaining: ['郭店、马王堆材料及注释史待专门核验。'], adjacentImpact: '环境、行动、语言页应避免把道家当作现成口号库。', nextPriority: '补写文本考古与政治解释的阅读路径。' },
  },
  'pt-interpretation': {
    status: '核验正文｜自审完成',
    scope: '本条讨论文本、传统与他人理解的证据和边界；不承诺每个对象有一条可无争议地提取的唯一意义，也不把解释者立场当成任意改写许可。',
    origin: [{ kind: '概括', text: '解释学以人的意图、信念、行动以及艺术、历史见证等意义对象为中心，讨论解释的性质、范围和有效性。理解既需处理文本部分与整体，也需面对解释者自身历史处境。', sourceIds: ['INT-1'] }],
    boundaries: [{ kind: '概括', text: '字面意义、作者意图、历史接受、当前使用和规范评价可彼此相关而不相同。解释任务不同，允许的证据和成功标准也不同。', sourceIds: ['INT-1'] }],
    objections: [{ kind: '概括', text: '意图取向被质疑无法处理意图证据缺失和文本后续意义；历史／视域取向则被质疑相对主义。回应不是任选一边，而是公开任务、语境证据、替代解释和可反驳后果。', sourceIds: ['INT-1'] }],
    confusions: [{ kind: '解释性重构', text: '解释有历史性不等于事实与文本证据无约束；解释循环是校正程序，不是任意循环。' }, { kind: '解释性重构', text: '批判性重读不必等于否认原文说了什么；可先准确说明，再评价其局限与后果。' }],
    historicalContext: [{ nodeId: 'pt-chinese-later', label: '两汉至近现代：传承、佛教与重构', note: '经典、注释、翻译与制度共同塑造“传统”的可理解性。' }, { nodeId: 'pt-language-meaning', label: '语言如何承载意义与真理？', note: '语义、语境与言语行为提供解释的部分限制。' }],
    sources: [source('INT-1', 'SEP：Hermeneutics', 'https://plato.stanford.edu/entries/hermeneutics/', '导论、§1–§4', '解释的对象、有效性、历史性及其同语言、历史、艺术和实践的关系。'), source('INT-2', 'SEP：Zhu Xi', 'https://plato.stanford.edu/entries/zhu-xi/', '§1、§3–§4；与王阳明的后续争论', '朱熹的经典注释、格物、修养实践与王阳明的不同解释；不将其预设为欧洲解释学。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '文本解释', issue: '原文把作者意图当作唯一终点。', evidence: 'INT-1 将解释放进历史、语言和实践的多重问题。', revision: '分开意图、接受史和当前规范使用。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原书单没有显示施莱尔马赫、狄尔泰、伽达默尔和朱熹分别在解决何种解释难题。', evidence: 'INT-1 区分语法／心理理解、历史人文科学、解释循环与视域；INT-2 核对朱熹的注释、格物与修养语境以及与王阳明的分歧。', revision: '新增四个比较单元、课堂案例用途及反投射边界。' }], remaining: ['中西经典诠释原典和翻译理论需逐文本核验。'], adjacentImpact: '“法律”“宗教与理性”页面应表明其解释权问题；“审美价值”应将评价理由同对作品的解释任务分开。', nextPriority: '补充翻译、证词和殖民档案的解释伦理。' },
  },
  'pt-legitimacy': {
    status: '核验正文｜自审完成',
    scope: '本条比较政治权力、权威、正当性与服从义务；不将有效统治、公众支持、法律有效性或道德上有权命令混同。',
    origin: [{ kind: '概括', text: '正当性问题来自强制性政治安排：制度凭什么限制、征税、惩罚或要求服从？描述性正当性关心人们的接受信念，规范性正当性则问权力能否被合理辩护。', sourceIds: ['LEG-1', 'LEG-2'] }],
    boundaries: [{ kind: '概括', text: '事实权威只说明命令被普遍服从；规范权威至少涉及正当强制、施加义务的规范权力或统治权。即使一项制度在某一意义上正当，也未必自动使每人有广泛服从义务。', sourceIds: ['LEG-1', 'LEG-2'] }],
    objections: [{ kind: '概括', text: '同意、民主、服务与公平理论均面对沉默、少数、能力不平等和历史不义；政治义务怀疑论由此区分可正当存在的制度与普遍服从责任。回应须交代异议、申诉和改变制度的渠道。', sourceIds: ['LEG-1', 'LEG-2'] }],
    confusions: [{ kind: '解释性重构', text: '多数赞成是重要社会事实，不等于已完成规范辩护。' }, { kind: '解释性重构', text: '反对一项法律不等于否认任何公共权威；服从义务也不等于禁止一切抗命。' }],
    historicalContext: [{ nodeId: 'pt-law', label: '法律、服从与公民抗命', note: '法律义务与政治权威需分别分析后再讨论抗命。' }, { nodeId: 'pt-islamic-reason-revelation', label: '存在、理智与启示的古典论辩', note: '权威、解释与规范理由在另一历史语境中提出不同问题。' }],
    sources: [source('LEG-1', 'SEP：Political Legitimacy', 'https://plato.stanford.edu/archives/spr2024/entries/legitimacy/', '导论、§1、§4', '描述／规范正当性、强制、权威及民主正当性。'), source('LEG-2', 'SEP：Authority', 'https://plato.stanford.edu/entries/authority/', '导论、§1', '事实／规范权威、正当强制、施加义务和统治权的区分。'), source('LEG-3', 'SEP：Political Obligation', 'https://plato.stanford.edu/entries/political-obligation/', '导论、§1.1–§1.3、§2', '政治义务的定义、怀疑论、同意理论以及霍布斯和洛克的不同契约路径。'), source('LEG-4', 'SEP：John Rawls', 'https://plato.stanford.edu/entries/rawls/', '§3.1、§3.3–§3.6', '合理多元、自由主义正当性原则、公共理由与重叠共识。'), source('LEG-5', 'SEP：Mencius', 'https://plato.stanford.edu/entries/mencius/', '§1、§2，尤其 1A7 的治理讨论', '孟子文本的时代、恻隐扩展、民生与治理责任；不将其预设为现代民主理论。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜正当性', issue: '原文把民众接受等同于有权统治。', evidence: 'LEG-1 区分韦伯式描述概念和规范辩护。', revision: '增加权威、强制与服从义务三层。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原人物卡只列名字与书名，无法看出安全、同意、公共理由和民生治理如何提出不同的正当性问题。', evidence: 'LEG-3 核对政治义务、霍布斯—洛克契约线与怀疑论；LEG-4 核对罗尔斯的合理多元和公共理由；LEG-5 核对《孟子》的治理语境。', revision: '新增四个比较单元、逐项来源和“不能直接推出”的边界，避免将孟子翻译成现代民主。' }], remaining: ['中国、伊斯兰、非洲政治哲学的原典比较尚待专门核验；霍布斯、洛克与孟子的中文原典版本尚未逐段对读。'], adjacentImpact: '“正义”“法律”不能从一项合法程序直接推出服从义务；“照护”页可从民生与依赖的不同语境连接，但不得合并概念。', nextPriority: '补写民主少数、国际机构与平台权威，并建立非西方政治思想的逐文本阅读卡。' },
  },
  'pt-justice': {
    status: '核验正文｜自审完成',
    scope: '本条讨论分配、平等、权利、支配和历史不义；不把正义缩为收入再分配，也不把个人选择与制度背景切开。',
    origin: [{ kind: '概括', text: '法律、制度和政策持续分配利益与负担，且这种分配深刻影响人生。分配正义为这些政治过程和结构提供道德指导，而不仅给结果排一份静态榜单。', sourceIds: ['JUS-1'] }],
    boundaries: [{ kind: '概括', text: '形式平等、资源／机会分配、关系平等、程序正义和历史修复评价的对象不同。只问“每人得到多少”会遗漏支配、参与和产生分配的制度。', sourceIds: ['JUS-1', 'JUS-2'] }],
    objections: [{ kind: '概括', text: '自由主义担忧平等目标侵犯权利与自我所有；平等主义担忧形式自由掩盖起点和支配；结构取向则需说明谁负责改变持续性不义。没有理论能只宣称一种价值而避开其余代价。', sourceIds: ['JUS-1', 'JUS-2'] }],
    confusions: [{ kind: '解释性重构', text: '平等不必要求所有结果相同，而要说明哪些不平等与权力关系可以被接受。' }, { kind: '解释性重构', text: '再分配不只发生在税后转移；产权、市场、家庭和政治规则事先塑造分配。', sourceIds: ['JUS-1'] }],
    historicalContext: [{ nodeId: 'pt-identity-oppression', label: '身份、压迫与认识不公如何形成？', note: '资源分配与承认、证言和制度权力相互交织。' }, { nodeId: 'pt-africana-race', label: '种族、殖民与解放', note: '历史剥夺和殖民性要求正义不只处理当前份额。' }],
    sources: [source('JUS-1', 'SEP：Distributive Justice', 'https://plato.stanford.edu/entries/justice-distributive/', '导论、§1–§3', '制度、政治过程和利益／负担分配的评价对象。'), source('JUS-2', 'SEP：Equality', 'https://plato.stanford.edu/entries/equality/', '导论及分配平等相关章节', '形式平等与分配正义的不同原则。'), source('JUS-3', 'SEP：John Rawls', 'https://plato.stanford.edu/entries/rawls/', '§4.6–§4.7', '无知之幕、原初状态、平等自由与正义原则的论证位置。'), source('JUS-4', 'SEP：Robert Nozick’s Political Philosophy', 'https://plato.stanford.edu/entries/nozick-political/', '§4.1–§4.2', '历史资格、取得、转让、纠正及对模式化分配的批评。'), source('JUS-5', 'SEP：Feminist Political Philosophy', 'https://plato.stanford.edu/entries/feminism-political/', '导论、§3 相关段落', '私人／公共边界、政治排除、艾丽斯·马里昂·杨对被边缘化声音和协商的批评。'), source('JUS-6', 'SEP：Mohism', 'https://plato.stanford.edu/entries/mohism/', '导论、§6–§7', '兼爱、利、社会秩序、政治领导与其对个人权利问题的边界。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '主要立场｜自由与平等', issue: '原文将其写为零和口号。', evidence: 'JUS-1 将焦点放在不同制度框架及其后果。', revision: '改为权利、机会、支配和分配对象的具体冲突。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '人物卡没有交代罗尔斯、诺齐克、杨和墨家的比较对象，也没有把“结构”落实到发声与制度条件。', evidence: 'JUS-3 核对原初状态；JUS-4 核对资格理论；JUS-5 核对杨对边缘化声音与协商的批评；JUS-6 核对墨家兼爱、利和秩序。', revision: '将人物改写为问题框架、案例用途和不可直接推出的结论，并在墨家项标记非现代权利语境。' }], remaining: ['全球正义、残障正义和修复正义的专门来源待补；杨的《正义与差异政治》与墨家原典的中文版本尚未逐段对读。'], adjacentImpact: '“好生活”“照护”“环境”应明确分配与结构性责任；“身份与压迫”页须保持资源、发声和历史伤害的区分。', nextPriority: '补写殖民修复、能力、残障与民主参与的独立论证卡。' },
  },
  'pt-law': {
    status: '核验正文｜自审完成',
    scope: '本条讨论法律有效性、道德评价、服从与抗命；不提供具体法律意见，也不把“现行有效”当作“道德上应服从”的结论。',
    origin: [{ kind: '概括', text: '法律系统创造、承认、变更和执行义务；但为何有法律、法律内容凭什么成立、是否有服从义务，是相互关联的哲学问题。', sourceIds: ['LAW-1', 'LAW-2'] }],
    boundaries: [{ kind: '概括', text: '法律实证主义主张法律存在与内容依赖社会事实而非功过；自然法／非实证主义则认为法律有效性的根据部分涉及道德。两者都不自动回答人是否应服从具体法律。', sourceIds: ['LAW-1', 'LAW-2'] }],
    objections: [{ kind: '概括', text: '实证主义被质疑难处理极端不义与解释性裁判；其回应是区分识别法律和批判法律。自然法路线被质疑会让个人道德偏好替代法律；其回应须说明可公共检验的道德理由。抗命理论还须处理风险、公开性、受害者和替代渠道。', sourceIds: ['LAW-1', 'LAW-2'] }],
    confusions: [{ kind: '解释性重构', text: '法律实证主义不等于“法律永远应被服从”，它只主张法律有效性不由道德优劣决定。', sourceIds: ['LAW-1'] }, { kind: '解释性重构', text: '公民抗命并非所有违法；秘密救援、革命、个人逃避与公开政治抗议需要不同理由。' }],
    historicalContext: [{ nodeId: 'pt-legitimacy', label: '何种权力与制度是正当的？', note: '权威与服从义务的区分决定法律问题的边界。' }, { nodeId: 'pt-legalism', label: '先秦：墨家、名家、法家等论辩线索', note: '法、术、势和现代法治不可直接等同。' }],
    sources: [source('LAW-1', 'SEP：Legal Positivism', 'https://plato.stanford.edu/entries/legal-positivism/', '导论、§2–§4', '法律依赖社会事实、可分离命题及“实证主义＝盲从”的误读。'), source('LAW-2', 'SEP：The Nature of Law', 'https://plato.stanford.edu/entries/lawphil-nature/', '导论、§1.1', '法律有效性、自然法／非实证主义和法律规范性的争论。'), source('LAW-3', 'SEP：Civil Disobedience', 'https://plato.stanford.edu/entries/civil-disobedience/', '导论、§1–§3，马丁·路德·金相关段落', '抗命与其他抗议形式的区分、正当化条件、数字抗命和金的直接行动。'), source('LAW-4', 'SEP：Legalism in Chinese Philosophy', 'https://plato.stanford.edu/entries/chinese-legalism/', '导论、§1、§4–§5', 'fa 的多重语义、后设“法家”分类、韩非的官僚治理与权力技术。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜法律与道德', issue: '原文将实证主义误写为不关心正义。', evidence: 'LAW-1 明确区分法律存在与法律是否应服从。', revision: '重写有效性、道德评价和义务的分工。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原人物卡把哈特、富勒、金和韩非并列为“法律观点”，遮蔽了他们分别讨论制度识别、规则引导、政治抗议和统治技术。', evidence: 'LAW-1 核对哈特的社会基础与反盲从；LAW-2 核对富勒的法律内在道德；LAW-3 核对抗命边界和金的直接行动；LAW-4 核对 fa 与韩非的历史语境。', revision: '新增四个比较单元、案例用途与边界，并明确韩非不能直接等同现代法治或实证主义。' }], remaining: ['民法传统、中国法思想和抗命原典尚待逐文本核验；《韩非子》、哈特、富勒和〈伯明翰监狱来信〉的中文版本尚未逐段对读。'], adjacentImpact: '“责任”“正当性”不可将法律制裁视为道德责备的简单翻译；“解释”页可承接法律解释，但不可把程序品质误写成终局正义。', nextPriority: '补写法律解释、紧急权力、吹哨者保护与数字抗命的来源账。' },
  },
  'pt-history-tech': {
    status: '核验正文｜自审完成',
    scope: '本条讨论技术、历史与共同生活的互构；不将技术理解为纯中性工具或脱离人类选择的自主命运，也不把社会解释误作否认材料与工程限制。',
    origin: [{ kind: '概括', text: '技术是经济、文化和政治力量，也是一组设计、制造、使用和维护实践。技术哲学既研究人工物、设计和知识，也研究风险、责任、操纵、权力与正义。', sourceIds: ['TEC-1'] }],
    boundaries: [{ kind: '概括', text: '技术与科学相互渗透但不相同；技术决定论、社会建构和技术中介各强调不同因果层面。问题应是哪些设计和制度路径被选择、由谁承担后果，而非把一方当成唯一原因。', sourceIds: ['TEC-1'] }],
    objections: [{ kind: '概括', text: '工具主义会把责任只推给使用者；决定论会抹去设计与政治选择；纯社会建构论则可能低估材料、成本和工程约束。较好的解释追踪技术构件、组织、法律、市场和使用者之间的可改变联系。', sourceIds: ['TEC-1'] }],
    confusions: [{ kind: '解释性重构', text: '技术具有政治后果不等于技术本身有道德意图；责任仍要沿设计、采购、部署和监管链追踪。' }, { kind: '解释性重构', text: '效率不是中性结论：它总以某些目标、时间、成本和被忽略的损失为尺度。' }],
    historicalContext: [{ nodeId: 'pt-ai-future', label: '人工智能能否行动、负责或拥有道德地位？', note: 'AI 治理需放回更宽的技术、劳动和制度史。' }, { nodeId: 'pt-environment-animals', label: '道德共同体应包括动物与自然吗？', note: '技术风险和基础设施改变环境责任与代际问题。' }],
    sources: [source('TEC-1', 'SEP：Philosophy of Technology', 'https://plato.stanford.edu/entries/technology/', '导论、§1–§3.2、§6.2', '技术哲学的不同取向、设计、风险、责任、权力和正义；海德格尔、温纳和哈拉维的争论位置。'), source('TEC-2', 'SEP：Mohism', 'https://plato.stanford.edu/entries/mohism/', '§2.1、§3.1 的 fa、工匠、经验依据与利', '墨家以工匠标准说明 fa，考察标准的经验根据、用途与社会利益；不等同现代技术哲学。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '主要立场｜技术决定论', issue: '原文把技术影响社会写成技术决定一切。', evidence: 'TEC-1 区分技术自身、设计实践和社会政治面向。', revision: '改为可追溯的社会技术链。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原书单没有解释为何海德格尔、温纳、哈拉维和墨家的材料能共同用于人脸识别案例。', evidence: 'TEC-1 分别定位框架、人工物的政治性、情境化知识与民主参与；TEC-2 核对 fa、工匠和利的历史语境。', revision: '新增四个比较单元，分开宏观揭示、设计权力、边界政治和标准—公共后果，并标记不可直接等同。' }], remaining: ['中国技术史、殖民基础设施与劳动史的专门资料待补。'], adjacentImpact: 'AI、环境和正义页应写明技术治理涉及产权、劳动和申诉机制；“知识从哪里来”可衔接标准、证据和实践，但不能以效果直接证明真理。', nextPriority: '补写平台、监控与基础设施正义。' },
  },
  'pt-care': {
    status: '核验正文｜自审完成',
    scope: '本条讨论照护、依赖、亲近关系和制度分工；不将照护浪漫化为无边界牺牲，也不把自主误解为不需要任何人。',
    origin: [
      { kind: '概括', text: '照护伦理从传统伦理常把正常主体设为独立、平等、可互惠的行动者这一遗漏出发。现实中依赖普遍存在，关系常不对称，而照护劳动又经由性别、阶级、种族与移民制度被不均分配。', sourceIds: ['CAR-1', 'CAR-2'] },
      { kind: '解释性重构', text: '问题不是是否应当关怀，而是怎样辨识需要、由谁回应、照护者的成本谁承担、被照护者如何保有声音与权力。' },
    ],
    boundaries: [
      { kind: '概括', text: '照护可指实践、关系、动机或政治规范；不同理论以满足重要需要为共同线索，却对亲密偏向、陌生人义务和制度责任有不同结论。', sourceIds: ['CAR-2'] },
      { kind: '概括', text: '关系自主不是否认自主，而是说形成和行使选择能力依赖支持、资源与承认。依赖不天然使人缺乏尊严，也不自动授权他人替其决定。', sourceIds: ['CAR-1'] },
    ],
    objections: [
      { kind: '概括', text: '照护伦理被批评会把女性化照护角色当作美德、容忍压迫性家庭，或缺少政治尺度。回应路径把照护劳动、结构性不平等和全球照护链放进公共制度，同时仍要警惕由国家或家庭控制被照护者。', sourceIds: ['CAR-1'] },
      { kind: '概括', text: '亲近偏向能说明特殊关系，却不能无限扩张成排外。它须同被依赖者的利益、照护者的自我保存和陌生人的可主张权利一起辩护。', sourceIds: ['CAR-2'] },
    ],
    confusions: [
      { kind: '解释性重构', text: '照护不是女性的天性，也不只是情绪；它包括知识、时间、身体劳动、判断和制度安排。' },
      { kind: '解释性重构', text: '承认依赖不等于取消被照护者的自主、同意或反对权。' },
      { kind: '解释性重构', text: '公正与照护不是互斥选项；照护理论往往正要求将被隐藏的劳动和不平等纳入正义。', sourceIds: ['CAR-1'] },
    ],
    historicalContext: [
      { nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '关系、孝与养成可提供资源，也需要性别、权力和边界的批评。' },
      { nodeId: 'pt-african-personhood', label: '人格、共同体与 Ubuntu', note: '关系性人格与照护可相互照亮，但不可消除不同概念与历史。' },
      { nodeId: 'pt-justice', label: '自由、平等与正义如何协调？', note: '照护劳动和资源分配属于制度正义问题。' },
    ],
    sources: [
      source('CAR-1', 'SEP：Feminist Ethics', 'https://plato.stanford.edu/entries/feminism-ethics/', '§2.2 及照护、依赖、结构性劳动相关段落', '照护伦理、关系自主、依赖与照护劳动的政治批评；吉利根、诺丁斯、基泰与照护链的讨论。'),
      source('CAR-2', 'SEP：Personal Relationship Goods', 'https://plato.stanford.edu/entries/personal-relationship-goods/', '导论、§2.1、§5–§6', '照护作为关系善、需要、特殊关系、照护分配与制度责任的规范问题。'),
      source('CAR-3', 'SEP：Mencius', 'https://plato.stanford.edu/entries/mencius/', '§1、§2，尤其 1A7 的恻隐与治理讨论', '孟子文本的时代、由具体受苦的恻隐到治理责任的讨论；不预设其为当代照护伦理。'),
    ],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '主要立场｜照护伦理', issue: '原文将照护处理为私人善意。', evidence: 'CAR-1 将依赖与劳动放进结构性不平等。', revision: '加入照护者、被照护者和制度责任。' }, { location: '案例｜家庭照护', issue: '原案例默认女儿应承担照护。', evidence: 'CAR-2 强调需要与关系善，不预设特定人承担全部成本。', revision: '要求比较分工、同意、资源和公共支持。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '人物卡只留下“关怀”的印象，未区分吉利根的研究批评、诺丁斯的关系偏向、基泰的派生依赖和孟子的修养—政治语境。', evidence: 'CAR-1 核对吉利根、诺丁斯、基泰和照护劳动的论述；CAR-2 核对照护的分配与制度承担；CAR-3 核对《孟子》的恻隐、民生与治理讨论。', revision: '新增四个比较单元、制度案例用途与各自不可直接推出的结论，避免把孟子或女性经验本质化。' }], remaining: ['东亚照护实践、残障正义和长期照护制度的原典／实证资料待补；《孟子》、吉利根、诺丁斯与基泰的中文原典版本尚未逐段对读。'], adjacentImpact: '“好生活”“正义”“自由”须承认依赖和支持关系；“正当行动”不能以抽象普遍性跳过照护者与被照护者的权力差异。', nextPriority: '增加照护链、残障、被照护者自决与长期照护制度的来源账和跨页案例。' },
  },
  'pt-art': {
    status: '核验正文｜自审完成',
    scope: '本条讨论艺术定义的竞争方案及其制度后果；不裁定某媒介或传统更高，也不把博物馆、市场或专家认可直接当作艺术价值的最终判据。',
    origin: [
      { kind: '概括', text: '再现、表达、形式、作者意图与制度认可都能解释某些典型艺术，却在现成品、概念艺术、仪式、民间技艺和参与式实践前遇到边界。艺术定义问题由此迫使我们说明分类为何重要以及谁掌握分类权。', sourceIds: ['ART-1'] },
      { kind: '解释性重构', text: '艺术地位影响保存、教育、资助、著作权和公共可见性；所以“只是定义”从来不只是词典问题。' },
    ],
    boundaries: [
      { kind: '概括', text: '功能性定义诉诸艺术典型发挥的功能；程序性定义诉诸艺术世界或历史关系；反定义取向质疑是否存在必要充分条件。它们解释的对象和目标不同。', sourceIds: ['ART-1'] },
      { kind: '解释性重构', text: '“艺术”与“艺术价值”“审美价值”“文化遗产”不可互换：一物可被承认为艺术却评价很低，也可有重要文化价值而不落进特定艺术制度。' },
    ],
    objections: [
      { kind: '概括', text: '制度理论能解释同物在展厅和商店的差异，却被质疑循环和保守：若艺术世界已排除某些传统，它如何纠正自身？历史／制度论者需说明开放、批评和新实践进入的机制。', sourceIds: ['ART-1'] },
      { kind: '概括', text: '以表达或审美功能定义可抓住经验，却可能排除反审美、政治和概念实践；反定义路线则须说明开放概念仍如何支持教育、保存和反伪造判断。', sourceIds: ['ART-1'] },
    ],
    confusions: [
      { kind: '解释性重构', text: '作者签名、昂贵价格或展厅位置并不自动证明艺术价值；它们可能说明历史／制度关系。' },
      { kind: '解释性重构', text: '“艺术是主观的”无法单独解决分类、解释和评价争议。' },
      { kind: '解释性重构', text: '将非西方技艺纳入艺术史不应只靠替换一个标签，而要重审媒介、用途、传承与展示权力。' },
    ],
    historicalContext: [
      { nodeId: 'pt-aesthetic-value', label: '审美判断能否说明理由？', note: '艺术是什么与艺术为何好相关，但不由同一理论解决。' },
      { nodeId: 'pt-interpretation', label: '我们如何理解文本、传统与他人？', note: '作品的意义、意图和接受史不能在定义问题中跳过。' },
      { nodeId: 'pt-history-tech', label: '历史、文化与技术怎样塑造共同生活？', note: '复制、平台与 AI 会重塑作者、媒介与制度。' },
    ],
    sources: [
      source('ART-1', 'SEP：The Definition of Art', 'https://plato.stanford.edu/entries/art-definition/', '导论、§1–§5', '功能、程序、历史与反定义方案及其反对。'),
      source('ART-2', 'Leo Tolstoy, What Is Art?', 'https://www.gutenberg.org/files/64908/64908-h/64908-h.htm', '第 V、X、XV 章及英译序言的 infection 讨论', '托尔斯泰把艺术理解为情感传达／感染，并以可理解性和道德—宗教判断批评精英艺术。'),
      source('ART-3', 'SEP：Zhuangzi', 'https://plato.stanford.edu/entries/zhuangzi/', '§2、§4.8；庖丁、轮扁、乐师与技艺讨论', '《庄子》关于多种技艺、熟练、流畅和限度的解释资源；并非现代艺术定义。'),
    ],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜艺术定义', issue: '原文只列形式、表达、制度三项，未说明为何竞争。', evidence: 'ART-1 区分功能、程序、历史与反定义目标。', revision: '补足分类对象和解释代价。' }, { location: '案例｜展厅椅子', issue: '原案例将制度说成任意许可。', evidence: 'ART-1 将制度理论置于历史关系和循环批评。', revision: '加入排除、开放与批评机制问题。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原书单将托尔斯泰、丹托、迪基和《庄子》并列，却没有指出三者讨论的对象不同。', evidence: 'ART-2 是情感感染与艺术价值的强规范性主张；ART-1 区分制度／历史、功能与反定义；ART-3 讨论技艺与多种实践路径。', revision: '新增四个比较单元：将《庄子》明确标为可比的技艺资源而非现代艺术定义，并为每一路线写出椅子案例用途和限制。' }], remaining: ['中国艺术史、工艺与仪式的原典／策展文献尚待独立核验。'], adjacentImpact: '“审美价值”不得把艺术类别当成价值保证。', nextPriority: '补写挪用、复制权与 AI 生成物的作者问题。' },
  },
  'pt-aesthetic-value': {
    status: '核验正文｜自审完成',
    scope: '本条讨论审美判断的理由、分歧与价值；不规定单一品味，也不把历史知识、身体经验和社会排除误当作与审美无关的噪音。',
    origin: [
      { kind: '概括', text: '审美判断似乎以感受为基础，却常邀请、甚至要求他人同意并给出理由。美、审美对象、态度、体验和价值本身又是不同概念，故分歧不仅是“喜欢不同”。', sourceIds: ['AES-1', 'AES-2'] },
      { kind: '解释性重构', text: '公共艺术、教育和批评使问题更紧迫：若完全私人化，无法说明学习和批评；若把标准交给权威，又会复制谁能进入审美共同体的不平等。' },
    ],
    boundaries: [
      { kind: '概括', text: '审美价值不必等于艺术价值、道德价值或市场价值。审美判断可关于艺术或自然，而“审美”概念本身包含对象、判断、态度、经验和值等相互竞争的用法。', sourceIds: ['AES-1', 'AES-2'] },
      { kind: '解释性重构', text: '评价理由可指作品特征、适当注意、背景知识、比较经验或解释性理解；列出理由不保证一定得到一致结论。' },
    ],
    objections: [
      { kind: '概括', text: '主观主义难说明“误读细节”“批评更好”何以可能；形式主义难说明历史、内容和社会位置；能力标准则可能将特定教育和阶级习惯伪装为普遍品味。回应应让理由可公开、可反驳而非只换一个权威。', sourceIds: ['AES-1', 'AES-2'] },
      { kind: '概括', text: '质疑者认为“审美”概念本身的用法过多、难以统一。保留它需要说明它在具体比较中做了何种不可替代的工作，而不是把一切积极体验都称为审美。', sourceIds: ['AES-2'] },
    ],
    confusions: [
      { kind: '解释性重构', text: '有理由的审美分歧不等于任何判断同样好；理由本身仍可遗漏特征、事实或受影响者。' },
      { kind: '解释性重构', text: '“无利害”不等于作品没有政治、道德或物质后果。' },
      { kind: '解释性重构', text: '专业知识可以帮助看见特征，却不自动取消非专业观众的经验和质疑。' },
    ],
    historicalContext: [
      { nodeId: 'pt-art', label: '什么是艺术？', note: '分类与价值相连但不相同。' },
      { nodeId: 'pt-interpretation', label: '我们如何理解文本、传统与他人？', note: '理解背景和解释争议会改变可感知的特征。' },
      { nodeId: 'pt-african-method', label: '什么算作非洲哲学？', note: '谁拥有评价标准与何种表达能进入经典，都是审美／制度问题。' },
    ],
    sources: [source('AES-1', 'SEP：Aesthetic Judgment', 'https://plato.stanford.edu/entries/aesthetic-judgment/', '导论、§1、§3', '品味判断、主观性、规范性、休谟与康德的分歧。'), source('AES-2', 'SEP：The Concept of the Aesthetic', 'https://plato.stanford.edu/entries/aesthetic-concept/', '导论、§1–§3', '审美对象、判断、态度、经验和价值的多重用法及质疑。'), source('AES-3', 'SEP：Aesthetics in Chinese Philosophy: Painting and Calligraphy', 'https://plato.stanford.edu/archives/spr2026/entries/chinese-painting-calligraphy/', '导论、§1–§3', '中国书画理论的过程、意、笔触、传递与观者关系；不归约为单一“中国审美”。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '主要立场｜主观／客观', issue: '原文把争论写成“有无标准”的二选一。', evidence: 'AES-1、AES-2 显示理由、经验和概念本身均有多层。', revision: '改为可交流、可质疑但未必一致的评价。' }, { location: '公共雕塑案例', issue: '原例遗漏位置、历史与谁被影响。', evidence: 'AES-2 反对将审美价值同所有其他价值混同。', revision: '保留审美理由，同时要求说明公共和历史维度。' }, { location: '新增｜哲学家怎样改写这个问题', issue: '原书单没有让休谟、康德、贝尔与中国书画论回答同一个公共审美案例。', evidence: 'AES-1 核对休谟的情感—标准张力与康德的主观普遍性；AES-2 记录形式与审美概念争议；AES-3 核对过程、笔触和传递关系。', revision: '新增四个比较单元，分别说明理由、可交流性、形式与过程，并明确跨传统不可直接等同。' }], remaining: ['中国诗画论和残障审美研究尚待逐文本补入。'], adjacentImpact: '“艺术”与“公共正义”需保留价值类型的区分再讨论冲突。', nextPriority: '增加跨文化批评和公共空间审美的来源账。' },
  },
  'pt-good-life': {
    status: '核验正文｜自审完成',
    scope: '本条讨论什么非工具性地对一个人好，以及这与道德、意义和社会条件的关系；不提供人生处方，也不把结构性剥夺归咎于个人没有做出“好选择”。',
    origin: [
      { kind: '概括', text: '“好生活”要求的不只是某件事有价值，而是它怎样使当事人的生活对其更好。福祉是“对某人好”的审慎价值，须同道德价值、审美价值和人生意义分开。', sourceIds: ['LIF-1'] },
      { kind: '解释性重构', text: '幸福、意义、德性与社会认可都可能相关，却不能自动互推：一种生活可愉快却空洞，可有意义却艰难，也可能因不义制度而缺少可选择方案。' },
    ],
    boundaries: [
      { kind: '概括', text: '当代讨论常区分享乐主义、欲望理论与客观清单理论。它们分别把体验、愿望满足或某些客观活动／关系置于福祉中心，但都须解释自主、信息、适应和分配。', sourceIds: ['LIF-1'] },
      { kind: '概括', text: '价值理论不只问什么“好”，还问好是对谁、以何种比较和理由成立。把“有益于我”混为“总体更好”会直接跳过伦理与政治争论。', sourceIds: ['LIF-2'] },
    ],
    objections: [
      { kind: '概括', text: '享乐主义受体验机器式反对：若体验相同却由欺骗或空洞操纵造成，许多人仍认为生活较差；欲望理论受无知、操纵和自我贬抑的愿望挑战；客观清单则须说明谁制定清单、如何尊重差异。没有一种反例可单独结束争论。', sourceIds: ['LIF-1'] },
      { kind: '解释性重构', text: '将福祉完全私人化会遗漏住房、健康、照护、劳动和歧视如何塑造选项；将它完全客观化又可能压过当事人的声音。两种风险都应进入具体判断。' },
    ],
    confusions: [
      { kind: '解释性重构', text: '福祉不等于健康、收入或愉快的单一指标；这些可能是构成、条件或手段，须分别论证。' },
      { kind: '解释性重构', text: '人生意义不同于“对我好”；牺牲性的照护或正义行动可能降低一时福祉，却仍有意义或道德价值。' },
      { kind: '解释性重构', text: '尊重偏好不等于接受所有偏好为有利于当事人，尤其在操纵、强迫和严重信息缺失下。' },
    ],
    historicalContext: [
      { nodeId: 'pt-western-ancient', label: '古典与希腊化时期', note: '德性、宁静与快乐提供不同古典入口，不能合并成单一“幸福论”。' },
      { nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '修养与社会物质条件的联结，为个人福祉与公共秩序提供不同路线。' },
      { nodeId: 'pt-death-meaning', label: '死亡会使生命失去还是获得意义？', note: '意义、有限性与福祉相邻但不相同。' },
    ],
    sources: [
      source('LIF-1', 'SEP：Well-Being', 'https://plato.stanford.edu/entries/well-being/', '导论、§1–§4', '福祉的“对人好”边界，以及享乐、欲望、客观清单理论。'),
      source('LIF-2', 'SEP：Value Theory', 'https://plato.stanford.edu/entries/value-theory/', '导论、§1–§2', '价值、福祉与其他评价性概念的区分。'),
      source('LIF-3', 'SEP：Aristotle’s Ethics', 'https://plato.stanford.edu/entries/aristotle-ethics/', '§2，尤其“Human Good and the Function Argument”', 'eudaimonia、德性活动、完整人生与外在善的作用。'),
      source('LIF-4', 'SEP：Epicurus', 'https://plato.stanford.edu/entries/epicurus/', '§4 “Psychology and Ethics”', '快乐、痛苦、审慎与伊壁鸠鲁伦理学的论证位置。'),
      source('LIF-5', 'SEP：The Meaning of Life', 'https://plato.stanford.edu/entries/life-meaning/', '关于主观条件、客观价值与 Wolf 混合理论的章节', '人生意义与福祉、正确性的区分；沃尔夫“主观投入／客观值得”的混合路径。'),
      source('LIF-6', 'SEP：Mencius', 'https://plato.stanford.edu/entries/mencius/', '§2 “The Virtues and Their Cultivation”', '仁义、端绪、养成、情感与政治判断的关联。'),
    ],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [
      { location: '主要立场｜主观／客观幸福', issue: '原文将二者写作纯粹的感受与权威清单。', evidence: 'LIF-1 对三类理论分别提出自主、信息和价值的难题。', revision: '改为比较理论所解释的价值与代价。' },
      { location: '案例推演｜职业选择', issue: '原例将生活选择视作完全个人可控。', evidence: '福祉概念讨论必须区分好本身与获得它的社会条件。', revision: '加入劳动、照护和可选择性的问题。' },
      { location: '新增｜哲学家怎样改写这个问题', issue: '原人物卡只提示原典，未说明其原有问题如何进入福祉争论，也没有逐项来源指向。', evidence: 'LIF-3 至 LIF-6 分别核对亚里士多德的兴盛与外在善、伊壁鸠鲁伦理、沃尔夫对意义的混合论及孟子的德性养成。', revision: '新增“原问题—对本页的推进—不能直接推出”比较，并将人物卡与论证路径接入来源账。' },
    ], remaining: ['残障正义、能力理论和儒家兴盛论的原典与当代争论仍待逐本核验。'], adjacentImpact: '“正当行动”不得把福祉假定为无争议单一数量；“照护”“正义”需把可选择性继续落实为制度问题。', nextPriority: '补写能力、残障、照护与结构不平等的来源账和跨页案例。' },
  },
  'pt-right-action': {
    status: '核验正文｜自审完成',
    scope: '本条比较后果、义务、德性与关系取向如何判断行动；不把任何理论当作快速道德算法，也不把具体受影响者、制度背景和不确定性排除在案例之外。',
    origin: [
      { kind: '概括', text: '行动可改善或恶化结果、尊重或侵犯他人、表达或塑造品格，并改变依赖关系。规范伦理的分歧正是关于何种事实在“应当做什么”中具有基础地位，而非关于谁是否关心后果、规则或美德。', sourceIds: ['ACT-1', 'ACT-2', 'ACT-3'] },
      { kind: '解释性重构', text: '困难案例暴露理论代价：一条规则若例外过多会失去约束力，只看总量可能忽略个体界限，只看品格则需给可争论的行动指导。' },
    ],
    boundaries: [
      { kind: '概括', text: '后果论主张规范性质只依赖后果；义务论围绕何为必须、禁止或允许的选择；德性伦理以德性和实践智慧为中心。三者可谈同一案例，但解释优先性不同。', sourceIds: ['ACT-1', 'ACT-2', 'ACT-3'] },
      { kind: '解释性重构', text: '行动的正确、行动者是否值得赞扬、制度是否正义、结果是否好，是不同评价对象。不能从“结果坏”直接推出某人应受最严厉谴责。' },
    ],
    objections: [
      { kind: '概括', text: '后果论须回答权利、承诺和分配为何不应为总量随时牺牲；义务论须面对义务冲突与灾难性后果；德性伦理须说明美德的识别不循环，且不会把既有偏见写成品格标准。各路线都可调整，但调整会改变其代价。', sourceIds: ['ACT-1', 'ACT-2', 'ACT-3'] },
      { kind: '解释性重构', text: '将复杂关系只看作后果或规则的背景，可能遗漏依赖、照护和权力；但诉诸关系也不能免于要求公允、可质疑和保护弱势者。' },
    ],
    confusions: [
      { kind: '解释性重构', text: '后果论不必等于粗糙地“多数压倒少数”，但它必须说明价值、分配和规则层面的处理。' },
      { kind: '解释性重构', text: '义务论不等于照本宣科；它的核心正是哪些限制能说明对人之尊重。' },
      { kind: '解释性重构', text: '德性伦理不是“做感觉像好人会做的事”，实践智慧需要理由、学习与可批评的判断。' },
    ],
    historicalContext: [
      { nodeId: 'pt-western-ancient', label: '古典与希腊化时期', note: '从德性与实践智慧读起，不把古典伦理只当作现代规则理论之前史。' },
      { nodeId: 'pt-legalism', label: '先秦：墨家、名家、法家等论辩线索', note: '兼爱、非攻、法与治理形成不同的规范问题，不能直接套进现代三分。' },
      { nodeId: 'pt-care', label: '关系、照护与依赖', note: '进一步问抽象原则如何面对具体依赖和权力关系。' },
    ],
    sources: [
      source('ACT-1', 'SEP：Consequentialism', 'https://plato.stanford.edu/entries/consequentialism/', '导论、§1–§3', '后果论的规范性依赖、价值问题和经典功利主义。'),
      source('ACT-2', 'SEP：Deontological Ethics', 'https://plato.stanford.edu/entries/ethics-deontological/', '导论、§1–§5', '义务论的选择评价、限制与后果不确定性。'),
      source('ACT-3', 'SEP：Virtue Ethics', 'https://plato.stanford.edu/entries/ethics-virtue/', '导论、§1–§3', '德性伦理同后果论、义务论的中心性差异和实践智慧。'),
      source('ACT-4', 'SEP：Kant’s Moral Philosophy', 'https://plato.stanford.edu/entries/kant-moral/', '§6 “The Humanity Formula”', '人格／人性作为目的本身、不得仅作手段及其限度。'),
      source('ACT-5', 'SEP：Mill’s Moral and Political Philosophy', 'https://plato.stanford.edu/entries/mill-moral-political/', '功利主义、高低快乐和自由相关章节', '密尔功利主义中的快乐、能力、自由与解释争议。'),
      source('ACT-6', 'SEP：Aristotle’s Ethics', 'https://plato.stanford.edu/entries/aristotle-ethics/', '§4–§5，德性、实践智慧与中道相关段落', '习惯、实践智慧、情感和具体情境在行动判断中的作用。'),
      source('ACT-7', 'SEP：Mohism', 'https://plato.stanford.edu/entries/mohism/', '导论、§1、§7', '墨家兼爱、利、非攻、标准与先秦政治—伦理语境。'),
    ],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [
      { location: '主要立场｜三种伦理', issue: '原内容把三者误写为只关心后果、规则、人格。', evidence: 'ACT-3 指出每种可讨论三类因素，区别在基础性。', revision: '改为比较评价优先性和理论代价。' },
      { location: '案例推演｜两难', issue: '原例诱导读者以直觉选边。', evidence: 'ACT-1、ACT-2 的分歧要求明确价值、限制与不确定性。', revision: '加入谁承担风险和事后修复，而非宣告唯一答案。' },
      { location: '新增｜哲学家怎样改写这个问题', issue: '原人物卡止于“谁主张什么”，未交代康德、密尔、亚里士多德与墨家各自改变了哪种评价优先性。', evidence: 'ACT-1 至 ACT-7 核对后果依赖、选择限制、德性中心性、人格公式、密尔的功利解释与墨家的先秦语境。', revision: '新增四项可比较但不强行等同的分析；每项明确可如何用于案例及不能替人物推出的结论。' },
    ], remaining: ['儒家、佛教及当代照护伦理的原典对读尚未完成；墨家与现代后果论的细部比较仍需逐段核验。'], adjacentImpact: '“正义”“法律”继续保留行动评价与制度评价的区别；“照护”页可承接关系与依赖的遗漏。', nextPriority: '补入照护、动物与全球正义的交叉案例，并逐文本扩展非西方原典路径。' },
  },
  'pt-responsibility': {
    status: '核验正文｜自审完成',
    scope: '本条讨论道德归责、赞许、谴责、修复和运气；不把因果贡献、法律有罪和应受道德责备混为同一结论。',
    origin: [
      { kind: '概括', text: '归责实践以行动者的能力、认识与行动来源为依据，却会受到结果、处境、性格和背景运气影响。道德运气问题由此出现：我们似乎只应评价可控制之事，实际判断却常随不可控因素改变。', sourceIds: ['RES-1', 'RES-2'] },
      { kind: '概括', text: '责任还包括不同“面向”：可归属性、可要求说明和可追究性许可不同反应，不应以单一的惩罚模型覆盖。', sourceIds: ['RES-1'] },
    ],
    boundaries: [
      { kind: '概括', text: '因果贡献可在缺少预见时成立；可责性通常还需控制和认识条件。道德运气可影响对行为、性格、结果或责任的判断，须先说清评价对象。', sourceIds: ['RES-1', 'RES-2'] },
      { kind: '概括', text: '控制原则说人只应就其可控制之事受到道德评价，但其适用范围本身有争议：即使成功与失败者可对不同结果负责，也未必应有不同程度的责备。', sourceIds: ['RES-2'] },
    ],
    objections: [
      { kind: '概括', text: '严格控制原则会因性格、机会和结果遍布行动而威胁大部分责任；接受运气则可能损害公平。回应包括区分责任对象与责备程度、重视理由响应与认识条件，或将重点转向前瞻防害与修复。', sourceIds: ['RES-1', 'RES-2'] },
      { kind: '概括', text: '责任怀疑论认为决定论、机会或运气排除足以支持基本应得的控制；即使接受此怀疑，社会仍需回答保护、补偿、信任和受害者承认如何安排。', sourceIds: ['RES-1'] },
    ],
    confusions: [
      { kind: '解释性重构', text: '“不应责备”不等于“没有伤害、无需补救或无人有责任”。' },
      { kind: '解释性重构', text: '后果改变法律责任或赔偿需求，不自动证明成功者在道德上更坏。', sourceIds: ['RES-2'] },
      { kind: '解释性重构', text: '理解创伤、操纵或制度背景要求更细的责任分配，不是取消行动者能动性。' },
    ],
    historicalContext: [
      { nodeId: 'pt-freedom', label: '因果、自由与责任', note: '自由理论提供一类控制条件，但责任还涉及认识、关系和制度。' },
      { nodeId: 'pt-justice', label: '自由、平等与正义如何协调？', note: '归责与惩罚、补偿和制度分配有连接，但不是同一议题。' },
      { nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '将过失放进改过、学习和关系中，可提供不同于应得惩罚的资源。' },
    ],
    sources: [
      source('RES-1', 'SEP：Moral Responsibility', 'https://plato.stanford.edu/entries/moral-responsibility/', '导论、§2–§3.10', '责任能力、反应、认识条件、怀疑论与道德运气。'),
      source('RES-2', 'SEP：Moral Luck', 'https://plato.stanford.edu/entries/moral-luck/', '导论、§1–§3', '控制原则、不同道德评价对象和结果运气的冲突。'),
      source('RES-3', 'SEP：Bernard Williams', 'https://plato.stanford.edu/entries/williams-bernard/', '§2–§3，尤其道德纯净与行动者悔恨相关段落', '威廉斯对系统道德、道德运气和行动者悔恨的批评性讨论。'),
    ],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [
      { location: '案例｜酒后驾驶', issue: '原内容只问成功与失败者谁更坏。', evidence: 'RES-2 区分对结果负责与责备程度。', revision: '拆分风险选择、实际伤害、赔偿与可责性。' },
      { location: '主要立场｜责任', issue: '原内容将责任等同报复性惩罚。', evidence: 'RES-1 区分可归属性、可回答性和可追究性。', revision: '增加说明、修复和前瞻性回应。' },
      { location: '新增｜哲学家怎样改写这个问题', issue: '原人物卡没有说明“结果有差异”与“应受同等责备”可同时成立，也未区分道德运气与修复要求。', evidence: 'RES-1 核对责任面向与反应态度；RES-2 核对控制原则、结果运气和评价对象；RES-3 核对威廉斯对道德纯净与行动者悔恨的批评。', revision: '新增康德、内格尔、斯特劳森、威廉斯的比较，并在每项中分开可责、损害、修复与权力问题。' },
    ], remaining: ['集体责任、修复性正义和中文伦理术语的专门资料尚待核验；威廉斯与内格尔的原文段落仍应纳入下一轮对读。'], adjacentImpact: '“法律”和“正当行动”不得将道德可责性直接视为法律处罚的充分条件；“自由”页需继续区分控制理论与责任实践。', nextPriority: '补写制度责任、受害者承认和修复性正义的独立来源账。' },
  },
  'pt-legalism': {
    status: '核验正文｜自审完成',
    scope: '本条是先秦墨家、名家与法家相关论辩的入口，重点说明法家／法术之学的分类和政治问题；不把它等同现代法治，也不把先秦思想缩为儒道二分。',
    sectionHeadings: { origin: '时段与论辩起点', boundaries: '分类与概念边界', objections: '内部差异与解释争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '战国竞争、战争与行政重组使富国强兵、秩序、官僚监督和统治者—臣属关系成为尖锐问题。后称“法家”的思想家以法、术、势及奖惩、职名等提出回应；同一时段的墨辩、名实论辩也以不同方式处理规范、语言与治理。', sourceIds: ['LEGZ-1'] }],
    boundaries: [{ kind: '概括', text: '“法家”是后设且不精确的分类；fa 不只指法律，也可指标准、方法、规范与制度。它并非自觉统一学派，故韩非、商鞅、申不害等之间不能当成同一套教义。', sourceIds: ['LEGZ-1'] }, { kind: '解释性重构', text: '本页不把墨家的兼爱、名家的名实和法家治理混作一个理论；它们被并置，是为了让读者看见先秦政治与论辩问题的多条路线。' }],
    objections: [{ kind: '概括', text: '法术之学以可执行标准和官僚制约抵抗任意人治，却被批评为把人主要理解为可操控的利害行动者，并削弱道德、关系与反对声音。反过来，只靠品格的治理观也要回答如何处理权力监督、制度激励和公开标准。', sourceIds: ['LEGZ-1'] }, { kind: '解释性重构', text: '解释上尤其应警惕：把“现实主义”赞成价值中立，或把对道德修辞的批评读成完全否认任何规范理由，都会快过现存文本所允许的结论。' }],
    confusions: [{ kind: '解释性重构', text: '法家不等于现代“法治”：后者涉及限制公权、权利与程序，而 fa 的语义和目标更宽、也不同。', sourceIds: ['LEGZ-1'] }, { kind: '解释性重构', text: '“百家”并非彼此封闭的十个盒子；文本归属、影响与后来分类都需分别核实。' }],
    historicalContext: [{ nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '礼、德性与治理的关系应与法、术、势形成真正比较。' }, { nodeId: 'pt-language-meaning', label: '语言如何承载意义与真理？', note: '名、实、职名和标准把语言问题接到行动与制度。' }, { nodeId: 'pt-law', label: '法律、服从与公民抗命', note: '现代法律有效性、权利与权威不可反向投射到法家。' }],
    sources: [source('LEGZ-1', 'SEP：Legalism in Chinese Philosophy', 'https://plato.stanford.edu/entries/chinese-legalism/', '导论、§1–§7', '“法家”分类的后设性、fa 的语义、战国语境、治理问题及历史接受。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜法家', issue: '旧文把法家直接译为现代法治。', evidence: 'LEGZ-1 明确说明 fa 比“law”宽，且该分类并非自觉学派。', revision: '改写为法、术、势与后设分类，加入现代投射的警告。' }, { location: '人物', issue: '旧文将商鞅、申不害、韩非当作完全一致。', evidence: 'LEGZ-1 分述文本与思想背景。', revision: '不作单一教义归纳，保留逐文本阅读待办。' }], remaining: ['《商君书》《韩非子》、墨经及名家材料的中文校勘与互证尚未完成。'], adjacentImpact: '“法律”“语言意义”“正当行动”不得把先秦路线套成现代政治哲学的直接前身。', nextPriority: '分设墨家论辩与名实、韩非文本阅读卡。' },
  },
  'pt-chinese-later': {
    status: '核验正文｜自审完成',
    scope: '本条概览两汉至近现代的中国思想传承、制度、佛教交流和重构；不是一条由“儒家复兴”统摄的直线，也不以“中国哲学”标签抹去区域、语言和实践差异。',
    sectionHeadings: { origin: '时段与重构起点', boundaries: '正典、制度与分期边界', objections: '线性叙事的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '汉代国家、经学、宇宙论、医学和政治辩论使先秦文本被重新编排、解释和制度化；许多今日习用的“儒、道、法”等学派分类也在此一时期形成。', sourceIds: ['CHL-1'] }, { kind: '概括', text: '宋明道学在佛教长期影响之后重估经典、宇宙论和心性工夫；其目标与争论不能只还原为“复古”，也不能与汉代或近现代视作同一种儒学。', sourceIds: ['CHL-2'] }],
    boundaries: [{ kind: '概括', text: '“中国哲学”既是研究对象的名称，也携带现代学科、翻译和正典建构的选择。这里的时间线只提供入口：经学、玄学、佛教、理学、考据、近代转型需要回到具体文本、制度和跨区域网络。', sourceIds: ['CHL-1', 'CHL-2'] }],
    objections: [{ kind: '概括', text: '以“传统停滞—西方冲击—现代化”叙事组织材料，会遮蔽翻译、注释、教育、考试、政治和区域流动中的持续创造；但只宣称延续也会抹掉权力、断裂和选择性遗忘。', sourceIds: ['CHL-1', 'CHL-2'] }, { kind: '解释性重构', text: '将理／气、心／理或工夫分歧抽成西方本体论／认识论的对应物，虽便于入门，却会改变它们在修养、经典解释和政治实践中的功能。' }],
    confusions: [{ kind: '解释性重构', text: '宋明理学不是单一“保守儒学”；朱熹、陆王及其后续解释的论证重心并不相同。', sourceIds: ['CHL-2'] }, { kind: '解释性重构', text: '汉代国家支持儒学不等于所有社会思想或所有政策都由一个一致意识形态决定。', sourceIds: ['CHL-1'] }],
    historicalContext: [{ nodeId: 'pt-confucian', label: '先秦：儒家及其伦理—政治问题', note: '先秦文本在后世被选择、注释并赋予新权威。' }, { nodeId: 'pt-buddhist', label: '佛教哲学：苦、无我、缘起与认识', note: '佛教思想与汉语思想世界的长期交涉不可作背景一笔带过。' }, { nodeId: 'pt-interpretation', label: '我们如何理解文本、传统与他人？', note: '经典、注释、教育制度与翻译共同塑造“传统”。' }],
    sources: [source('CHL-1', 'SEP：Philosophy in Han Dynasty China', 'https://plato.stanford.edu/entries/han-dynasty/', '导论、§1 及相关章节', '汉代国家、文本、学派分类与知识领域的关系。'), source('CHL-2', 'SEP：Song-Ming Confucianism', 'https://plato.stanford.edu/entries/song-ming-confucianism/', '导论、§1–§3', '道学／宋明儒学的范围、思想家、工夫与同佛教的论辩。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '历史叙事', issue: '旧文以朝代串接人物，缺少传承机制。', evidence: 'CHL-1、CHL-2 都把文本、教育与国家／论敌置于思想形成之中。', revision: '改为正典化、注释、制度与跨传统接触的入口。' }, { location: '理学', issue: '旧文把“理学”当作单一教义。', evidence: 'CHL-2 区分广义与狭义、人物及目标。', revision: '保留内部路线和逐文本待办。' }], remaining: ['魏晋玄学、汉传佛教、清代考据与近现代思想尚未逐支建立专门来源账。'], adjacentImpact: '“解释”“心与自我”“好生活”页引用后世中国思想时必须标明时期与论者。', nextPriority: '按汉、魏晋—隋唐、宋明、清—近现代分别建立深度线索。' },
  },
  'pt-indian-vedanta': {
    status: '核验正文｜自审完成',
    scope: '本条以奥义书和吠檀多诸传统为入口讨论梵、我、世界、知识与解脱；不把“印度思想”缩为不二论，也不将修行目标简化成脱离世界的形而上学结论。',
    sectionHeadings: { origin: '文本与问题起点', boundaries: '传统与术语边界', objections: '内部论辩与翻译风险', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '吠檀多以奥义书、梵经及其注释传统为权威背景，围绕自我、终极实在、无明、认识与解脱展开多种路线。商羯罗的不二论具有深远影响，但并不耗尽吠檀多。', sourceIds: ['VED-1', 'VED-2'] }],
    boundaries: [{ kind: '概括', text: '不二论中“我／自我”不是有意识性质的实体，而被理解为意识或显现原则；把它立即译为笛卡尔式心灵或现代个人，都会丢失论证的解脱和经释语境。', sourceIds: ['VED-1'] }, { kind: '概括', text: '吠檀多内部有不二、二元和多种介于其间的路线，它们对梵、世界、个体与敬爱实践的关系给出不同模型。', sourceIds: ['VED-2'] }],
    objections: [{ kind: '概括', text: '不二论面对的挑战包括：若经验世界并非最终真实，错误、行动、伦理和救度如何说明？不同吠檀多路线以实在层级、依赖关系、神人关系或敬爱实践提出不同答复，不能用“一切皆幻觉”概括。', sourceIds: ['VED-1', 'VED-2'] }, { kind: '解释性重构', text: '将奥义书的一句格言直接当作整套稳定形而上学，会跳过长期注释、经义冲突和论证形式。' }],
    confusions: [{ kind: '解释性重构', text: '不二不等于日常经验不存在，也不自动导向道德无关紧要；须问不同真理层级和实践目标。', sourceIds: ['VED-1'] }, { kind: '解释性重构', text: '“印度哲学主张万物一体”既抹去吠檀多内部差异，也抹去佛教、正理、耆那与顺世等竞争传统。' }],
    historicalContext: [{ nodeId: 'pt-mind-self', label: '心、自我与人格同一性', note: '与自我问题并置时须保留意识、解脱与经释的不同任务。' }, { nodeId: 'pt-being-change', label: '什么存在？变化与同一性如何可能？', note: '梵、世界与依赖的争论提供不同形而上学词汇。' }, { nodeId: 'pt-buddhist', label: '佛教哲学：苦、无我、缘起与认识', note: '自我与解脱问题相邻，却不能把不同传统互译为简单正反面。' }],
    sources: [source('VED-1', 'SEP：Personhood in Classical Indian Philosophy', 'https://plato.stanford.edu/entries/personhood-india/', '吠檀多与自我相关章节', '不二吠檀多的自我—意识论述及其同其他印度传统的比较。'), source('VED-2', 'SEP：God and Other Ultimates', 'https://plato.stanford.edu/entries/god-ultimates/', '吠檀多相关章节', '不二、二元及其他吠檀多路线的多样性。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '人物｜商羯罗', issue: '旧文把商羯罗等同于全部印度传统。', evidence: 'VED-2 说明吠檀多有多种不同模型。', revision: '将其定位为重要路线而非总称。' }, { location: '概念｜我与梵', issue: '旧文将其直译为现代个体心灵与宇宙。', evidence: 'VED-1 将自我置于意识、显现与解脱论证中。', revision: '补充术语与实践边界。' }], remaining: ['《奥义书》《梵经》、商羯罗和罗摩努阇的可靠中文译本与章段对应尚待核验。'], adjacentImpact: '“自我”“存在”“知识来源”不能用西方心身二分替代吠檀多的论证任务。', nextPriority: '增设不二、制限不二与二元路线的原典对读。' },
  },
  'pt-jain-carvaka': {
    status: '核验正文｜自审完成',
    scope: '本条连接耆那哲学的多面性、非暴力与认识论争议，以及顺世论／Cārvāka的物质主义重构问题；不把多面性读成“所有判断都对”，也不把主要由对手保存的顺世论材料写成无争议教义。',
    sectionHeadings: { origin: '文本与问题起点', boundaries: '材料保存与概念边界', objections: '论辩与证据的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '耆那教以马哈维拉为重要传统起点，围绕非暴力、业、解脱、认识有限性和多面性发展理论；其语言与认识论讨论强调表述视角的限制。', sourceIds: ['JAI-1'] }, { kind: '概括', text: '顺世论常被概括为古典印度的物质主义者，反对吠陀权威、业和解脱，并将人理解为有意识的身体；但其文本大量经批评者转述，重构必须标示证据条件。', sourceIds: ['JAI-2', 'JAI-3'] }],
    boundaries: [{ kind: '概括', text: '多面性（anekāntavāda）与“从某一方面说”的限定并非取消真假差别，而要求说明断言的对象、条件和视角；它不等于宽泛的相对主义。', sourceIds: ['JAI-1'] }, { kind: '概括', text: '关于顺世论的具体推理、人物和分支，材料不完整。能确认对手批评的对象，不等于能无保留复原其全部立场。', sourceIds: ['JAI-2', 'JAI-3'] }],
    objections: [{ kind: '概括', text: '多面性被质疑若每个立场都只在局部为真，如何批评错误、暴力或自相矛盾？回应须给出限定条件、证据和实践后果，而不是把“多角度”当作结束讨论。', sourceIds: ['JAI-1'] }, { kind: '概括', text: '顺世论反对超感官实体和经文权威，会逼迫其他传统说明推论、证言与仪式知识的根据；但由对手文本来证明这一挑战时，也须分清对手的讽刺与可归属内容。', sourceIds: ['JAI-2'] }],
    confusions: [{ kind: '解释性重构', text: '非暴力不是只指不直接伤害，也不自动给出所有政策或职业冲突的唯一答案。' }, { kind: '解释性重构', text: '材料主义不是简单“只相信肉眼可见”，其认识论主张仍要按证据与论证重建。' }],
    historicalContext: [{ nodeId: 'pt-knowledge-sources', label: '知识从哪里来，边界又在哪里？', note: '感知、推论、证言和有限视角在不同传统中被竞争性地安排。' }, { nodeId: 'pt-right-action', label: '什么使行动正确？', note: '非暴力把行动、意图、后果与关系连接起来。' }, { nodeId: 'pt-nyaya', label: '正理、胜论及认识—论辩传统', note: '论证与证据的分歧需保留各传统自身的术语。' }],
    sources: [source('JAI-1', 'SEP：The Literal-Nonliteral Distinction in Classical Indian Philosophy', 'https://plato.stanford.edu/entries/literal-nonliteral-india/', '导论及耆那教、语言限制相关章节', '耆那传统、表述限制与多面性问题。'), source('JAI-2', 'SEP：Personhood in Classical Indian Philosophy', 'https://plato.stanford.edu/entries/personhood-india/', '§2.3 Cārvāka', '顺世论的身体、自我、业与解脱主张。'), source('JAI-3', 'SEP：Naturalism in Classical Indian Philosophy', 'https://plato.stanford.edu/entries/naturalism-india/', '顺世论相关章节', '意识从物质元素出现的叙述及其解释争议。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜多面性', issue: '旧文把多面性写作所有主张同样正确。', evidence: 'JAI-1 将其置于限定表述和语言限制的讨论。', revision: '加入条件、对象和可批评性的要求。' }, { location: '顺世论', issue: '旧文把对手转述当直接原典。', evidence: 'JAI-2、JAI-3 的资料性质仅支持谨慎重构。', revision: '在范围与待办中显式标出保存偏差。' }], remaining: ['耆那原典和顺世论转述的文献谱系、中文译本尚待逐项核验。'], adjacentImpact: '“知识来源”“自我”页面要区分直接文本、对手转述和教学概括。', nextPriority: '补写 syādvāda、非暴力与顺世论证据史。' },
  },
  'pt-islamic-translation': {
    status: '核验正文｜自审完成',
    scope: '本条讨论希腊、叙利亚、波斯等知识在阿拉伯语哲学环境中的翻译、改写与学科形成；不把它称作被动保存，也不假设译文与希腊原文或后来拉丁文本意义相同。',
    sectionHeadings: { origin: '传译网络与问题起点', boundaries: '语言、文本与制度边界', objections: '“保存”叙事的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '翻译运动首先常经由叙利亚语材料，后来也直接面向亚里士多德文本及晚期古代注释。翻译、校订、术语选择、评注和教学共同构成 falsafa 的形成条件，而非单向搬运。', sourceIds: ['ISL-1', 'ISL-2'] }],
    boundaries: [{ kind: '概括', text: '“阿拉伯哲学”可指以阿拉伯语工作的思想活动，而“伊斯兰哲学”涉及更广文明与宗教语境；两者都不等于所有作者的族群或信仰身份。每次谈影响还须说明文本、语言、时间和中介。', sourceIds: ['ISL-1'] }, { kind: '概括', text: '翻译不是词对词替换：不同版本可有直译、释译与重编，哲学术语也会在逻辑、医学、神学和政治语境中改变功能。', sourceIds: ['ISL-2'] }],
    objections: [{ kind: '概括', text: '“希腊—阿拉伯保存—拉丁复兴”的故事把阿拉伯语思想家降为运输者，遗漏了评论、改造与原创论证；但反过来把一切都叫作独立于希腊的创造，也会抹去具体的文本依赖和翻译劳动。', sourceIds: ['ISL-1', 'ISL-2'] }, { kind: '解释性重构', text: '以宗教与哲学冲突来解释全部翻译史，会遮蔽宫廷、城市、教育、医学和跨宗教译者的实际网络。' }],
    confusions: [{ kind: '解释性重构', text: '翻译运动不是“知识自动从东方流向西方”；选择、资金、读者和解释权决定什么被译、如何被读。' }, { kind: '解释性重构', text: '阿拉伯语哲学家讨论亚里士多德，并不等于他们的论证只是亚里士多德的复写。' }],
    historicalContext: [{ nodeId: 'pt-western-medieval', label: '中世纪：传译、神学与大学', note: '多语传译网络应由此对读，而非中心—边缘叙事。' }, { nodeId: 'pt-islamic-reason-revelation', label: '存在、理智与启示的古典论辩', note: '翻译的概念进入形而上学、逻辑与启示解释的争论。' }, { nodeId: 'pt-interpretation', label: '我们如何理解文本、传统与他人？', note: '版本、译法和受众决定跨语文本能说什么。' }],
    sources: [source('ISL-1', 'SEP：Greek Sources in Arabic and Islamic Philosophy', 'https://plato.stanford.edu/entries/arabic-islamic-greek/', '导论及翻译运动相关章节', '希腊来源、翻译运动与 falsafa 形成。'), source('ISL-2', 'SEP：Arabic and Islamic Philosophy of Language and Logic', 'https://plato.stanford.edu/entries/arabic-islamic-language/', '导论及翻译运动相关章节', '叙利亚语—阿拉伯语中介、亚里士多德文本与逻辑语言语境。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '历史功能', issue: '旧文把翻译者与哲学家写成希腊知识的保管员。', evidence: 'ISL-1、ISL-2 都描述了选择、译法和学科重构。', revision: '改为传译、评注与概念创造的网络。' }, { location: '称谓', issue: '旧文将阿拉伯语、伊斯兰与族群身份混同。', evidence: 'ISL-1 的范围要求回到具体语言与传统。', revision: '增加称谓和身份的边界提示。' }], remaining: ['侯奈因等译者的具体译本、机构和年代须在专门史料中逐项核验。'], adjacentImpact: '“中世纪”“语言意义”页不可把跨语概念当作无摩擦的同一词。', nextPriority: '建立一部希腊文本在叙利亚语—阿拉伯语—拉丁语中的版本阅读卡。' },
  },
  'pt-islamic-reason-revelation': {
    status: '核验正文｜自审完成',
    scope: '本条比较古典阿拉伯／伊斯兰哲学和神学中关于存在、因果、理智、启示与解释权限的论辩；不把哲学家与神学家排成两个固定阵营，也不把当代“科学对宗教”框架倒灌进去。',
    sectionHeadings: { origin: '论辩起点与对象', boundaries: '哲学、神学与解释权限', objections: '内部差异与张力', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '阿拉伯形而上学围绕亚里士多德《形而上学》的传入、注释与改造发展；阿尔金迪、法拉比、伊本·西那等对存在、第一原理和科学体系给出不同方案，并与启示神学发生多层交涉。', sourceIds: ['ISR-1'] }, { kind: '概括', text: '哲学神学与启示宗教的兼容性并非只由“信或不信”决定，而涉及形而上学范围、证明标准、经文解释和神属性等具体问题。', sourceIds: ['ISR-1'] }],
    boundaries: [{ kind: '概括', text: 'falsafa、kalām、法学与苏菲传统有交叠也有区别；称它们“理性”或“信仰”不能代替说明各自论证方法与文本权威。', sourceIds: ['ISR-1'] }, { kind: '解释性重构', text: '“因果”“必然”“神意”在不同论者的技术含义并不固定；一个例子只能展示争点，不能代替对伊本·西那、安萨里、伊本·鲁世德等的原典阅读。' }],
    objections: [{ kind: '概括', text: '哲学的必然性与自然因果受到神意、创造和奇迹问题的挑战；将形而上学缩成神学又会失去关于存在、科学与论证范围的争论。不同论者一方面试图协调真理，另一方面也对解释权和方法等级有真实分歧。', sourceIds: ['ISR-1'] }, { kind: '解释性重构', text: '把安萨里只写成“反理性”、把伊本·鲁世德只写成“理性胜利”，会遮蔽他们的文本对象、神学承诺和具体论证。' }],
    confusions: [{ kind: '解释性重构', text: '真理一致性的主张不意味着所有读者都可用同一解释方法，也不意味着冲突已被消除。', sourceIds: ['ISR-1'] }, { kind: '解释性重构', text: '把自然规律讨论化约为“是否相信奇迹”，会遗漏因果、证明和科学分类的精细分歧。' }],
    historicalContext: [{ nodeId: 'pt-islamic-translation', label: '翻译运动与哲学学科的形成', note: '概念史须回到翻译、评注和教育网络。' }, { nodeId: 'pt-religion-reason', label: '信仰、理性与恶的问题', note: '可比较自然神学与解释权，但不能忽略不同宗教语境。' }, { nodeId: 'pt-being-change', label: '什么存在？变化与同一性如何可能？', note: '存在、因果与第一原理在此有不同技术传统。' }],
    sources: [source('ISR-1', 'SEP：Arabic and Islamic Metaphysics', 'https://plato.stanford.edu/entries/arabic-islamic-metaphysics/', '导论、§1–§6', '亚里士多德形而上学的阿拉伯传入、哲学神学与启示宗教关系、主要路线。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '立场对立', issue: '旧文把哲学与神学写作稳定的两方。', evidence: 'ISR-1 展示不同文本方法、哲学神学与启示关系。', revision: '改为具体问题和解释权限的多层争论。' }, { location: '人物', issue: '旧文将安萨里概括为否认一切理性。', evidence: 'ISR-1 所涉争论是特定形而上学和神学议题。', revision: '删除总括性标签，保留原典待办。' }], remaining: ['伊本·西那、安萨里、伊本·鲁世德作品的章段及阿拉伯文／中文译本尚待逐项对照。'], adjacentImpact: '“宗教与理性”“科学与实在”页的跨传统连接须标明比较不是等同。', nextPriority: '以因果与经文解释各建一张原典论证卡。' },
  },
  'pt-islamic-later': {
    status: '核验正文｜自审完成',
    scope: '本条处理后古典阿拉伯—伊斯兰形而上学及其在奥斯曼、伊朗等语境的延续与变革；不接受“伊本·鲁世德之后哲学终结”的叙事，也不以一条形而上学史覆盖现代改革、法学和政治思想。',
    sectionHeadings: { origin: '延续与转向', boundaries: '时段、地域与学科边界', objections: '衰落叙事的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '阿拉伯形而上学在古典阶段之后并未停止：亚里士多德文本的威望、伊本·西那的百科全书式重构、照明哲学及后来的本质—存在争论构成持续演变的多条路径。', sourceIds: ['ISL2-1', 'ISL2-2'] }],
    boundaries: [{ kind: '概括', text: '“后古典”覆盖不同语言、地区、教育制度和学科；以阿拉伯语形而上学为主的来源不能单独支持对苏菲、奥斯曼、近现代改革或整个伊斯兰世界的完整结论。', sourceIds: ['ISL2-1', 'ISL2-2'] }],
    objections: [{ kind: '概括', text: '“翻译到拉丁世界后思想中心转移，伊斯兰哲学衰落”的说法忽视后续评注、教学和新的形而上学竞争；但反驳衰落叙事也不能把所有时期与地区说成同样活跃或同一种创新。', sourceIds: ['ISL2-1', 'ISL2-2'] }, { kind: '概括', text: '后期本质—存在讨论内部就有不同方法与方案；以伊本·西那为唯一尺度会遗漏苏赫拉瓦迪及后续哲学的改变。', sourceIds: ['ISL2-2'] }],
    confusions: [{ kind: '解释性重构', text: '“后古典”不等于“注释而无哲学”；评论传统也可以提出新的论证和问题结构。' }, { kind: '解释性重构', text: '形而上学的持续不等于能代表同时期所有宗教、法律、政治和科学思想。' }],
    historicalContext: [{ nodeId: 'pt-islamic-reason-revelation', label: '存在、理智与启示的古典论辩', note: '古典争点在后续传统中被再组织，而非自动结束。' }, { nodeId: 'pt-western-medieval', label: '中世纪：传译、神学与大学', note: '跨语影响须追踪具体文本和中介。' }, { nodeId: 'pt-history-tech', label: '历史、文化与技术怎样塑造共同生活？', note: '现代性与改革另需政治、制度和媒介的专门资料。' }],
    sources: [source('ISL2-1', 'SEP：Arabic and Islamic Metaphysics', 'https://plato.stanford.edu/entries/arabic-islamic-metaphysics/', '导论、历史阶段与后伊本·西那相关章节', '阿拉伯形而上学的传承、伊本·西那转折和后续发展。'), source('ISL2-2', 'SEP：Essence and Existence in Arabic and Islamic Philosophy', 'https://plato.stanford.edu/entries/arabic-islamic-essence/', '导论及后古典方法相关章节', '本质—存在争论延续至近世伊朗语境及方法竞争。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '分期', issue: '旧文把伊本·鲁世德之后描述为哲学终结。', evidence: 'ISL2-1、ISL2-2 追踪后续形而上学与方法竞争。', revision: '改为延续、变形与不同覆盖范围。' }, { location: '现代性', issue: '旧文把后古典形而上学直接当现代改革史。', evidence: '当前来源主要支持形而上学线索。', revision: '在范围与待办中明确资料边界。' }], remaining: ['照明哲学、苏菲形而上学、奥斯曼及近现代改革的各自原典和社会史待补。'], adjacentImpact: '“中世纪”页不得以欧洲时间线判定其他传统的“结束”。', nextPriority: '分别建立苏赫拉瓦迪、穆拉·萨德拉与近现代改革的来源账。' },
  },
  'pt-african-method': {
    status: '核验正文｜自审完成',
    scope: '本条讨论何种材料、作者性、批判性和表达形式能被识别为非洲哲学；不把口述传统自动浪漫化为哲学，也不以欧洲学院写作作为唯一准入门槛。',
    sectionHeadings: { origin: '问题与证据起点', boundaries: '方法与材料边界', objections: '标准之争', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '奥鲁卡的“智者哲学”计划通过访谈、记录和概念追问，反驳非洲思想缺乏理性、口述即不能哲学或共同体必然压制批评的殖民偏见；它同时要求把个人理由与集体世界观区分开。', sourceIds: ['AFM-1'] }],
    boundaries: [{ kind: '概括', text: '格言、叙事、仪式和口述对话可以是哲学材料，却不自动就是已完成的哲学论证。需要追问谁说、何种异议存在、记录／翻译怎样改变表达，以及理由能否被检验与反驳。', sourceIds: ['AFM-1'] }, { kind: '解释性重构', text: '“非洲哲学”也不是一套统一内容；大陆内外的语言、历史、离散经验与学术实践需要分别定位。' }],
    objections: [{ kind: '概括', text: '强调个人论证可抵抗把传统整体化的民族哲学，却可能再次由研究者决定谁配得上“哲学家”；强调群体知识可反抗殖民排除，却可能掩盖内部性别、阶级、代际或政治分歧。可取的做法是公开材料链和解释者位置。', sourceIds: ['AFM-1'] }, { kind: '概括', text: '口述访谈有记录者选择、翻译和编辑问题。把它类比苏格拉底对话可启发方法，却不证明两种历史与权力关系相同。', sourceIds: ['AFM-1'] }],
    confusions: [{ kind: '解释性重构', text: '反对欧洲中心主义不等于拒绝论证或证据；关键是评判标准如何形成、能否反思、是否排除材料。' }, { kind: '解释性重构', text: '“口述”不等于匿名或无个人批判；但记录为文字也不自动消除失真。', sourceIds: ['AFM-1'] }],
    historicalContext: [{ nodeId: 'pt-african-personhood', label: '人格、共同体与 Ubuntu', note: '共同体概念必须通过具体论者、语言和争议来处理。' }, { nodeId: 'pt-interpretation', label: '我们如何理解文本、传统与他人？', note: '翻译、记录和诠释权是方法论问题。' }, { nodeId: 'pt-knowledge-sources', label: '知识从哪里来，边界又在哪里？', note: '证言、经验与批判如何互相约束，是跨传统问题。' }],
    sources: [source('AFM-1', 'SEP：African Sage Philosophy', 'https://plato.stanford.edu/entries/african-sage/', '导论、§1–§5', '奥鲁卡计划、口述与识字、民族哲学、批判思维及其方法争议。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '材料标准', issue: '旧文以“口述／书写”二分哲学与非哲学。', evidence: 'AFM-1 专门讨论口述、识字与批判反思。', revision: '改为材料链、作者性、理由和记录权力的多重检验。' }, { location: '民族哲学', issue: '旧文将批评民族哲学写成否定非洲思想。', evidence: 'AFM-1 指出争点是集体化、匿名化与批判性。', revision: '保留反殖民动机与内部批评的双重必要。' }], remaining: ['非洲大陆不同区域、女性思想家和当代非洲哲学方法论的专门资料待扩展。'], adjacentImpact: '所有非洲相关页面不得以单一谚语或 Ubuntu 标语概括多元传统。', nextPriority: '补入洪通吉、奥鲁卡及当代批评的原典节选与翻译说明。' },
  },
  'pt-african-personhood': {
    status: '核验正文｜自审完成',
    scope: '本条讨论非洲伦理中人格、品格、共同善、义务与关系性语言的多种解释；不把 Ubuntu 或共同体主义当作整个大陆的单一“本质”，也不让关系性取消弱势者的尊严与异议。',
    sectionHeadings: { origin: '道德语言与问题起点', boundaries: '人格、共同体与权利的边界', objections: '关系性解释的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '非洲伦理的研究可从不同社会的道德语言、品格、人格、社会关系、共同善与责任出发；它需要把伦理观念同对这些观念的哲学解释区分开，也不能从文化多样性直接推出没有可比较问题。', sourceIds: ['AFP-1'] }],
    boundaries: [{ kind: '概括', text: '“人格”可指所有人的地位、道德成熟的成就、社会承认或多种关系能力；这些含义不同。把人格说成由共同体“授予”时，必须说明儿童、残障者、异议者和被排斥者是否拥有不可取消的要求。', sourceIds: ['AFP-1'] }, { kind: '概括', text: '共同善、义务和人道主义在不同社会伦理语言中的关系并不等于否认权利；将“义务伦理”与“没有个人保护”画等号会跳过理论争论。', sourceIds: ['AFP-1'] }],
    objections: [{ kind: '概括', text: '强共同体取向被批评可能把社会角色、顺从或道德成熟当作承认人格的前提，进而伤害边缘者；温和关系取向则要交代冲突时谁有最后解释权、怎样保障退出和批评。', sourceIds: ['AFP-1'] }, { kind: '解释性重构', text: '把 Ubuntu 用于和解、公司管理或国家话语时，需要分别检验它是否仍保护历史伤害的受害者、承认权力不对称并允许不同共同体成员说“不”。' }],
    confusions: [{ kind: '解释性重构', text: '关系性人格不等于个人没有边界或只能服从共同体；关系也可成为压迫、剥夺或互相问责的场域。' }, { kind: '解释性重构', text: '“非洲伦理”是解释性总称，不是所有非洲社会共享的一套不变规则。', sourceIds: ['AFP-1'] }],
    historicalContext: [{ nodeId: 'pt-care', label: '关系、照护与依赖', note: '两者都重视关系，却来自不同道德语言和政治问题。' }, { nodeId: 'pt-good-life', label: '什么是值得过的生活？', note: '品格、共同善与个人福祉可以相连而不相同。' }, { nodeId: 'pt-african-method', label: '什么算作非洲哲学？', note: '概念的材料、翻译与作者性决定如何比较人格理论。' }],
    sources: [source('AFP-1', 'SEP：African Ethics', 'https://plato.stanford.edu/entries/african-ethics/', '导论、§3–§9', '品格、道德人格、人道主义、共同善、社会性与义务的讨论及其解释范围。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: 'Ubuntu', issue: '旧文把 Ubuntu 当作整套无争议的共同体主义。', evidence: 'AFP-1 的讨论从具体道德语言、人格与共同善出发。', revision: '改为多种解释，并加入权力和异议的检验。' }, { location: '人格', issue: '旧文没有区分地位、成就与承认。', evidence: 'AFP-1 区分道德人格与社会伦理概念。', revision: '明确不同含义与弱势者保护问题。' }], remaining: ['Akan、南部非洲 Ubuntu 语境及门基蒂、吉耶凯等的原典与中文翻译待逐项核验。'], adjacentImpact: '“照护”“自我”“正义”页不得把关系性简化为反个人主义标签。', nextPriority: '增加人格、权利、性别和残障之间冲突的具体论证卡。' },
  },
  'pt-africana-race': {
    status: '核验正文｜自审完成',
    scope: '本条讨论种族分类、殖民、反黑人主义和解放如何成为哲学问题，并以 Africana 哲学作为跨大陆与离散网络的研究入口；不将种族视为固定生物本质，也不将所有非洲与非裔经验合为一个声音。',
    sectionHeadings: { origin: '历史暴力与问题起点', boundaries: '种族、Africana 与经验边界', objections: '概念与政治的争议', confusions: '常见误读', historicalContext: '相邻传统与问题' },
    origin: [{ kind: '概括', text: '种族概念历史上常以生物基础、离散群体、遗传和地理起源来划分人类；这套分类与支配性制度紧密交织。即使拒绝其生物本质主义，也仍须解释种族化如何在法律、空间、劳动和认识实践中产生真实后果。', sourceIds: ['AFR-1'] }, { kind: '概括', text: 'Africana 哲学是涵盖非洲及其离散社群多种批判、思想与表达实践的元哲学伞概念，不是一套单一学说；殖民、奴役和反抗塑造了其问题场，也要求避免把差异压平。', sourceIds: ['AFR-2'] }],
    boundaries: [{ kind: '概括', text: '“种族是社会建构”不等于任意虚构或没有伤害；它要求追问社会如何建构、哪些制度维持、谁承担后果。生物、社会、法律与自我认同的分类也不能混作一个问题。', sourceIds: ['AFR-1'] }, { kind: '概括', text: 'Africana 不等于地理上的“非洲哲学”，也不等于只研究种族；它涵盖不同历史、离散、性别、阶级、艺术和政治实践。', sourceIds: ['AFR-2'] }],
    objections: [{ kind: '概括', text: '废除种族术语的方案希望摆脱本质主义，却被质疑会掩盖正在运行的不平等；保留或重建种族概念则须避免重固化伤害性分类。争论因此需同时处理概念准确性、政治后果和受影响者的解释权。', sourceIds: ['AFR-1'] }, { kind: '概括', text: '反殖民解放不能只等于国家独立或个人态度变化：法农的工作把种族化主体、语言、身体、暴力与社会重建并置。但以民族统一回应殖民也可能压制内部多样性和新的统治关系。', sourceIds: ['AFR-2', 'AFR-3'] }],
    confusions: [{ kind: '解释性重构', text: '种族没有固定生物本质，不等于种族主义的伤害“不真实”或无需修复。', sourceIds: ['AFR-1'] }, { kind: '解释性重构', text: '引用法农的暴力分析不能跳过其殖民语境，也不自动为任何现实暴力背书。', sourceIds: ['AFR-3'] }],
    historicalContext: [{ nodeId: 'pt-identity-oppression', label: '身份、压迫与认识不公如何形成？', note: '种族化连接社会分类、知识权力与制度分配。' }, { nodeId: 'pt-justice', label: '自由、平等与正义如何协调？', note: '纠正历史和结构性不义需要比较分配、修复与政治承认。' }, { nodeId: 'pt-african-method', label: '什么算作非洲哲学？', note: '正典与方法之争影响谁的思想可被看见为哲学。' }],
    sources: [source('AFR-1', 'SEP：Race', 'https://plato.stanford.edu/entries/race/', '导论及种族概念的历史定义相关章节', '生物本质主义的历史构成及种族概念的哲学问题。'), source('AFR-2', 'SEP：Africana Philosophy', 'https://plato.stanford.edu/entries/africana/', '导论、§1、§7–§13', 'Africana 作为元哲学领域、殖民与离散历史、概念范围。'), source('AFR-3', 'SEP：Frantz Fanon', 'https://plato.stanford.edu/entries/frantz-fanon/', '导论及殖民、种族与主体性相关章节', '法农对种族主义、殖民及其克服的多层分析。')],
    review: { mode: '自审（尚未独立复审）', checkedOn: '2026-09-07', findings: [{ location: '概念｜社会建构', issue: '旧文把社会建构误写成“种族不真实”。', evidence: 'AFR-1 区分生物本质主义与社会历史后果。', revision: '改为制度性建构与实际伤害。' }, { location: '传统范围', issue: '旧文把 Africana 当作单一非洲共同体观点。', evidence: 'AFR-2 将其界定为跨大陆、离散和多种实践的伞概念。', revision: '增加范围、差异与方法边界。' }], remaining: ['杜波依斯、塞泽尔、法农和女性主义／酷儿／残障 Africana 思想的原典与中文译本待逐项核验。'], adjacentImpact: '“身份与压迫”“正义”“历史与技术”页需把种族化写成结构与经验的交叉问题。', nextPriority: '建立种族实在论、废除论、修复正义与反殖民的独立论证卡。' },
  },
};
